--- Plugins
--- Add
vim.pack.add {
  { src = 'https://github.com/nvim-treesitter/nvim-treesitter' },
  { src = 'https://github.com/L3MON4D3/LuaSnip' },
  { src = 'https://github.com/stevearc/conform.nvim' },
  { src = 'https://github.com/sschleemilch/slimline.nvim' },
  { src = 'https://github.com/rose-pine/neovim' },
  { src = 'https://github.com/windwp/nvim-autopairs' },
  { src = 'https://github.com/supermaven-inc/supermaven-nvim' },
  { src = 'https://github.com/nvim-lua/plenary.nvim' },
  { src = 'https://github.com/onsails/lspkind.nvim' },
  { src = 'https://github.com/RRethy/nvim-treesitter-endwise' },
  { src = 'https://github.com/lewis6991/gitsigns.nvim' },
  { src = 'https://github.com/tummetott/unimpaired.nvim' },
  { src = 'https://github.com/kevinhwang91/nvim-ufo' },
  { src = 'https://github.com/kevinhwang91/promise-async' },
  { src = 'https://github.com/echasnovski/mini.nvim' },
  { src = 'https://github.com/sindrets/diffview.nvim' },
  { src = 'https://github.com/rmagatti/auto-session' },
  { src = 'https://github.com/folke/snacks.nvim' },
  { src = 'https://github.com/goolord/alpha-nvim' },
  { src = 'https://github.com/nvim-tree/nvim-web-devicons' },
  { src = 'https://github.com/elixir-tools/elixir-tools.nvim' },
  { src = 'https://github.com/nvim-neotest/neotest' },
  { src = 'https://github.com/nvim-neotest/nvim-nio' },
  { src = 'https://github.com/antoinemadec/FixCursorHold.nvim' },
  { src = 'https://github.com/fredrikaverpil/neotest-golang' },
  { src = 'https://github.com/jfpedroza/neotest-elixir' },
  { src = 'https://github.com/nvim-neotest/neotest-python' },
  { src = 'https://github.com/rcasia/neotest-java' },
  { src = 'https://github.com/folke/trouble.nvim' },
}
