return {
  { import = 'plugins.dev.lsp' },
  { import = 'plugins.dev.cypher' },
  { import = 'plugins.dev.clang' },
  { import = 'plugins.dev.java' },
  { import = 'plugins.dev.golang' },
  { import = 'plugins.dev.git' },
  { import = 'plugins.dev.dap' },
  { import = 'plugins.dev.rust' },
  { import = 'plugins.dev.typescript' },
  { import = 'plugins.dev.lint' },
  { import = 'plugins.dev.misc' },
  { import = 'plugins.dev.completion' },
  { import = 'plugins.dev.testing' },
}
