words = [
    "autopairs",
    "bufnr",
    "cterm",
    "diffview",
    "elixirls",
    "endwise",
    "formatters",
    "gitcommit",
    "gitsigns",
    "gofmt",
    "goimports",
    "gomod",
    "gosum",
    "keymap",
    "keymaps",
    "lspkind",
    "luasnip",
    "neotest",
    "neovim",
    "nextls",
    "noremap",
    "nvim",
    "prettierd",
    "quickfile",
    "relativenumber",
    "rustfmt",
    "setreg",
    "shfmt",
    "supermaven",
    "taplo",
    "unimpared",
    "vimdoc",
    "wincmd",
]
