words = [
    "autocmd",
    "autopairs",
    "autosnippets",
    "basedpyright",
    "botright",
    "bufnr",
    "buftype",
    "buildmode",
    "cgo",
    "colorcolumn",
    "completeopt",
    "conceallevel",
    "cterm",
    "cursorline",
    "cwd",
    "dattr",
    "diffview",
    "dirbuf",
    "dirvish",
    "dockerls",
    "dtrans",
    "echom",
    "elixirls",
    "endwise",
    "eob",
    "expandtab",
    "fillchars",
    "foldcolumn",
    "foldenable",
    "foldlevel",
    "foldlevelstart",
    "formatters",
    "gitcommit",
    "gitsigns",
    "gofmt",
    "goimports",
    "gomod",
    "gopls",
    "gosum",
    "gradlew",
    "ignorecase",
    "jdtls",
    "jsonls",
    "jumpto",
    "keymap",
    "keymaps",
    "lazygit",
    "lexplore",
    "lspkind",
    "luasnip",
    "mapleader",
    "maplocalleader",
    "mvn",
    "mvnw",
    "neotest",
    "neovim",
    "nextls",
    "nodiscard",
    "noremap",
    "noselect",
    "numhl",
    "nvim",
    "prettierd",
    "quickfile",
    "raml",
    "relativenumber",
    "rustfmt",
    "scrolloff",
    "setreg",
    "shellcheck",
    "shfmt",
    "signcolumn",
    "smartcase",
    "sourcer",
    "spm",
    "supermaven",
    "swapfile",
    "taplo",
    "ufo",
    "undofile",
    "unimpared",
    "updateevents",
    "updatetime",
    "vimdoc",
    "virt",
    "vitest",
    "vsplit",
    "winborder",
    "wincmd",
    "writebackup",
    "yamlls",
]
